apiVersion: apps/v1
kind: Deployment
metadata:
  name: full-deploy-app
  labels:
    app: full-deploy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: full-deploy-app
  template:
    metadata:
      labels:
        app: full-deploy-app
    spec:
      containers:
      - name: full-deploy-app
        image: asmaezaidi/mock-app:8
        ports:
        - containerPort: 8080